# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         EAFDSS
version:      0.80
version_from: lib/EAFDSS.pm
installdirs:  site
requires:
    Carp:                          1.04
    Class::Base:                   0.03
    Config::IniFiles:              2.38
    Digest::SHA1:                  2.11
    IO::Socket::INET:              1.31
    Socket:                        1.78
    Switch:                        2.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
